### ISSUE TITLE
Provided example uses "rabbitmqctl status" as livenessProbe and readinessProbe

### ISSUE THREAD

**Issue by pessoa** [rabbitmq/rabbitmq-peer-discovery-k8s#25] opened 2018-04-15 11:12 UTC
https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/blob/400693bbf91f6d0522a81c32116c087583decff5/examples/k8s_statefulsets/rabbitmq_statefulsets.yaml#L82
uses 'rabbitmqctl status' as livenessProbe and readinessProbe. However, a cluster node may be returning 0 on 'rabbitmqctl status' and not having joined the cluster.

Example (the reason why this happened is beyond this issue):
```
$ kubectl exec -n rmq rabbitmq-1 -- rabbitmqctl status
Status of node rabbit@172.16.200.5 ...
[{pid,324},
 {running_applications,
     [{inets,"INETS  CXC 138 49","6.4.4"},
      {cowboy,"Small, fast, modern HTTP server.","2.2.2"},
      {amqp_client,"RabbitMQ AMQP Client","3.7.4"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.7.4"},
      {ranch_proxy_protocol,"Ranch Proxy Protocol Transport","1.4.4"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.4.0"},
      {ssl,"Erlang/OTP SSL application","8.2.2"},
      {public_key,"Public key infrastructure","1.5.1"},
      {asn1,"The Erlang ASN1 compiler version 5.0.3","5.0.3"},
      {jsx,"a streaming, evented json parsing toolkit","2.8.2"},
      {recon,"Diagnostic tools for production use","2.3.2"},
      {mnesia,"MNESIA  CXC 138 12","4.15.1"},
      {xmerl,"XML parser","1.3.15"},
      {cowlib,"Support library for manipulating Web protocols.","2.1.0"},
      {crypto,"CRYPTO","4.1"},
      {os_mon,"CPO  CXC 138 46","2.4.3"},
      {lager,"Erlang logging framework","3.5.1"},
      {goldrush,"Erlang event stream processor","0.1.9"},
      {compiler,"ERTS  CXC 138 10","7.1.3"},
      {syntax_tools,"Syntax tools","2.1.3"},
      {sasl,"SASL  CXC 138 11","3.1"},
      {stdlib,"ERTS  CXC 138 10","3.4.2"},
      {kernel,"ERTS  CXC 138 10","5.4"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 20 [erts-9.1.5] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:64] [hipe] [kernel-poll:true]\n"},
 {memory,
     [{connection_readers,0},
      {connection_writers,0},
      {connection_channels,0},
      {connection_other,2840},
      {queue_procs,0},
      {queue_slave_procs,0},
      {plugins,17608},
      {other_proc,21117232},
      {metrics,183144},
      {mgmt_db,0},
      {mnesia,67736},
      {other_ets,2078472},
      {binary,414056},
      {msg_index,0},
      {code,28418634},
      {atom,1123529},
      {other_system,21374669},
      {allocated_unused,20139168},
      {reserved_unallocated,0},
      {strategy,rss},
      {total,[{erlang,74797920},{rss,77967360},{allocated,94937088}]}]},
 {alarms,[]},
 {listeners,[]},
 {vm_memory_calculation_strategy,rss},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,1554146918},
 {disk_free_limit,50000000},
 {disk_free,9454571520},
 {file_descriptors,
     [{total_limit,1048476},
      {total_used,0},
      {sockets_limit,943626},
      {sockets_used,0}]},
 {processes,[{limit,1048576},{used,150}]},
 {run_queue,0},
 {uptime,522},
 {kernel,{net_ticktime,60}}]
```
```
$ kubectl exec -n rmq rabbitmq-1 -- rabbitmqctl node_health_check
Error: this command requires the 'rabbit' app to be running on the target node. Start it with 'rabbitmqctl start_app'.
Arguments given:
        node_health_check
Usage:
rabbitmqctl [-n <node>] [-t <timeout>] [-q] node_health_check
command terminated with exit code 64
```
this raises the doubt of what's the best liveness and readiness probe.

If we consider a cluster already formed, one cloud say that both could be 'rabbitmqctl cluster_status'. But this doesn't take into account a forming cluster where that command would prevent the initial node from starting and then the cluster to form.

Between 'status', 'node_health_check' and 'cluster_status' (are there other candidates?), how should the choice be made?

For completeness here's 'node_health_check' for that failing node:
```
$ kubectl exec -n rmq rabbitmq-1 -- rabbitmqctl node_health_check
Error: this command requires the 'rabbit' app to be running on the target node. Start it with 'rabbitmqctl start_app'.
Arguments given:
        node_health_check
Usage:
rabbitmqctl [-n <node>] [-t <timeout>] [-q] node_health_check
command terminated with exit code 64
```

**Comment by michaelklishin** [comment] 2018-04-15 11:18
There is `rabbitmqctl cluster_status` but parsing CLI tool output is usually a terrible idea. See https://github.com/rabbitmq/rabbitmq-cli/issues/235, once it is implemented various provisioning tools and examples will be able to switch to it.

Please post questions to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users) in the future.

**Comment by michaelklishin** [comment] 2018-04-15 11:18
This is effectively a duplicate of https://github.com/rabbitmq/rabbitmq-cli/issues/235.

**Closed as completed by michaelklishin** 2018-04-15 11:18 UTC
Labels: duplicate

**Comment by michaelklishin** [comment] 2018-04-15 11:21
It's worth noting that there can be a chicken-and-egg problem between the way certain provisioning tools use status checks and actual cluster formation. I'm not a Kubernetes expert but after https://github.com/rabbitmq/rabbitmq-cli/issues/235 is implemented there has to be a discussion period (on the mailing list) that will identify potential risks and pitfalls.
